#!/usr/bin/env python3
"""Catalogue the App Intents actions installed apps expose to Shortcuts.

Reads every Metadata.appintents/extract.actionsdata bundle under /Applications and
/System/Applications (generated by Xcode from each app's AppIntent types) and emits, per
action, what a .shortcut file needs:

  WFWorkflowActionIdentifier  = "<bundle identifier>.<intent type name>"
  WFWorkflowActionParameters  = the intent's parameter names as keys, plus
      AppIntentDescriptor = {TeamIdentifier, BundleIdentifier, Name, AppIntentIdentifier,
                             ActionRequiresAppInstallation}
This matches the encoding used by Apple's gallery shortcuts (see dump-gallery.py).
For Apple's own apps the authoritative list is data/apple-app-intents.json, read from the
Shortcuts app's registry by dump-toolkit-registry.py, which also covers installed third-party
apps locally (data/toolkit-registry.json); this script reads the on-disk metadata directly and
does not need Shortcuts.app to have run.

usage: dump-appintents-actions.py [OUT.json]
"""
import glob
import json
import os
import plistlib
import subprocess
import sys

ROOTS = ["/Applications/*.app", "/System/Applications/*.app", "/System/Applications/Utilities/*.app",
         "/Applications/*.app/Contents/PlugIns/*.appex", "/System/Applications/*.app/Contents/PlugIns/*.appex"]


def localized(value):
    if isinstance(value, dict):
        return value.get("key") or value.get("string") or json.dumps(value)
    return value


def bundle_info(app):
    plist = os.path.join(app, "Contents", "Info.plist")
    try:
        info = plistlib.load(open(plist, "rb"))
    except Exception:
        return {}
    return {"bundleIdentifier": info.get("CFBundleIdentifier"), "name": info.get("CFBundleDisplayName") or info.get("CFBundleName")}


def team_identifier(app):
    try:
        out = subprocess.run(["codesign", "-dv", app], capture_output=True, text=True).stderr
        for line in out.splitlines():
            if line.startswith("TeamIdentifier="):
                return line.split("=", 1)[1].strip()
    except Exception:
        pass
    return None


def main(argv):
    catalog = []
    for pattern in ROOTS:
        for app in glob.glob(pattern):
            meta = os.path.join(app, "Contents", "Resources", "Metadata.appintents", "extract.actionsdata")
            if not os.path.exists(meta):
                continue
            info = bundle_info(app)
            team = team_identifier(app)
            data = json.load(open(meta))
            actions = data.get("actions") or {}
            for key, a in (actions.items() if isinstance(actions, dict) else enumerate(actions)):
                type_name = a.get("identifier") or key
                params = []
                for p in a.get("parameters", []):
                    params.append({"name": p.get("name"), "title": localized(p.get("title")), "optional": p.get("isOptional"),
                                   "valueType": p.get("valueType"), "isInput": p.get("isInput")})
                catalog.append({
                    "app": info.get("name"), "bundleIdentifier": info.get("bundleIdentifier"),
                    "shortcutActionIdentifier": f"{info.get('bundleIdentifier')}.{type_name}",
                    "appIntentDescriptor": {"TeamIdentifier": team, "BundleIdentifier": info.get("bundleIdentifier"),
                                            "Name": info.get("name"), "AppIntentIdentifier": type_name,
                                            "ActionRequiresAppInstallation": True},
                    "title": localized(a.get("title")), "description": localized((a.get("descriptionMetadata") or {}).get("descriptionText")),
                    "discoverable": a.get("isDiscoverable"), "openAppWhenRun": a.get("openAppWhenRun"),
                    "parameters": params, "availability": a.get("availabilityAnnotations"),
                })
    print(f"{len(catalog)} app-provided actions from {len({c['bundleIdentifier'] for c in catalog})} apps")
    if len(argv) > 1:
        json.dump(catalog, open(argv[1], "w"), indent=1)
        print("wrote", argv[1])
    else:
        for c in catalog[:8]:
            print(f"  {c['shortcutActionIdentifier']}  ({c['title']}) params={[p['name'] for p in c['parameters']]}")


if __name__ == "__main__":
    main(sys.argv)
